/**
 * Management API
 *
 * Configure and manage your Adyen company and merchant accounts, stores, and payment terminals. ## Authentication Each request to the Management API must be signed with an API key. [Generate your API key](https://docs.adyen.com/development-resources/api-credentials#generate-api-key) in the Customer Area and then set this key to the `X-API-Key` header value.  To access the live endpoints, you need to generate a new API key in your live Customer Area. ## Versioning  Management API handles versioning as part of the endpoint URL. For example, to send a request to this version of the `/companies/{companyId}/webhooks` endpoint, use:  ```text https://management-test.adyen.com/v3/companies/{companyId}/webhooks ```  ## Going live  To access the live endpoints, you need an API key from your live Customer Area. Use this API key to make requests to:  ```text https://management-live.adyen.com/v3 ```  ## Release notes Have a look at the [release notes](https://docs.adyen.com/release-notes/management-api) to find out what changed in this version!
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.adyen.model.management


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param actionType The type of terminal action: **InstallAndroidApp**, **UninstallAndroidApp**, **InstallAndroidCertificate**, or **UninstallAndroidCertificate**.
 * @param config Technical information about the terminal action.
 * @param confirmedAt The date and time when the action was carried out.
 * @param id The unique ID of the terminal action.
 * @param result The result message for the action.
 * @param scheduledAt The date and time when the action was scheduled to happen.
 * @param status The status of the terminal action: **pending**, **successful**, **failed**, **cancelled**, or **tryLater**.
 * @param terminalId The unique ID of the terminal that the action applies to.
 */
@Serializable
data class ExternalTerminalAction (

    /* The type of terminal action: **InstallAndroidApp**, **UninstallAndroidApp**, **InstallAndroidCertificate**, or **UninstallAndroidCertificate**. */
    @SerialName(value = "actionType") val actionType: kotlin.String? = null,

    /* Technical information about the terminal action. */
    @SerialName(value = "config") val config: kotlin.String? = null,

    /* The date and time when the action was carried out. */
    @SerialName(value = "confirmedAt") val confirmedAt: kotlin.String? = null,

    /* The unique ID of the terminal action. */
    @SerialName(value = "id") val id: kotlin.String? = null,

    /* The result message for the action. */
    @SerialName(value = "result") val result: kotlin.String? = null,

    /* The date and time when the action was scheduled to happen. */
    @SerialName(value = "scheduledAt") val scheduledAt: kotlin.String? = null,

    /* The status of the terminal action: **pending**, **successful**, **failed**, **cancelled**, or **tryLater**. */
    @SerialName(value = "status") val status: kotlin.String? = null,

    /* The unique ID of the terminal that the action applies to. */
    @SerialName(value = "terminalId") val terminalId: kotlin.String? = null

)

