/**
 * Management API
 *
 * Configure and manage your Adyen company and merchant accounts, stores, and payment terminals. ## Authentication Each request to the Management API must be signed with an API key. [Generate your API key](https://docs.adyen.com/development-resources/api-credentials#generate-api-key) in the Customer Area and then set this key to the `X-API-Key` header value.  To access the live endpoints, you need to generate a new API key in your live Customer Area. ## Versioning  Management API handles versioning as part of the endpoint URL. For example, to send a request to this version of the `/companies/{companyId}/webhooks` endpoint, use:  ```text https://management-test.adyen.com/v3/companies/{companyId}/webhooks ```  ## Going live  To access the live endpoints, you need an API key from your live Customer Area. Use this API key to make requests to:  ```text https://management-live.adyen.com/v3 ```  ## Release notes Have a look at the [release notes](https://docs.adyen.com/release-notes/management-api) to find out what changed in this version!
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.adyen.model.management


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param disputeEmail The email address for disputes.
 * @param region The region of operation. For example, **NA**, **EU**, **CH**, **AU**.
 * @param supportEmail The email address of merchant support.
 * @param autoCapture Indicates the status of [Automatic capture](https://docs.adyen.com/online-payments/capture#automatic-capture). Default value: **false**.
 */
@Serializable
data class KlarnaInfo (

    /* The email address for disputes. */
    @SerialName(value = "disputeEmail") @Required val disputeEmail: kotlin.String,

    /* The region of operation. For example, **NA**, **EU**, **CH**, **AU**. */
    @SerialName(value = "region") @Required val region: KlarnaInfo.Region,

    /* The email address of merchant support. */
    @SerialName(value = "supportEmail") @Required val supportEmail: kotlin.String,

    /* Indicates the status of [Automatic capture](https://docs.adyen.com/online-payments/capture#automatic-capture). Default value: **false**. */
    @SerialName(value = "autoCapture") val autoCapture: kotlin.Boolean? = null

) {

    /**
     * The region of operation. For example, **NA**, **EU**, **CH**, **AU**.
     *
     * Values: NA,EU,CH,AU
     */
    @Serializable
    enum class Region(val value: kotlin.String) {
        @SerialName(value = "NA") NA("NA"),
        @SerialName(value = "EU") EU("EU"),
        @SerialName(value = "CH") CH("CH"),
        @SerialName(value = "AU") AU("AU");
    }
}

