/**
 * Management API
 *
 * Configure and manage your Adyen company and merchant accounts, stores, and payment terminals. ## Authentication Each request to the Management API must be signed with an API key. [Generate your API key](https://docs.adyen.com/development-resources/api-credentials#generate-api-key) in the Customer Area and then set this key to the `X-API-Key` header value.  To access the live endpoints, you need to generate a new API key in your live Customer Area. ## Versioning  Management API handles versioning as part of the endpoint URL. For example, to send a request to this version of the `/companies/{companyId}/webhooks` endpoint, use:  ```text https://management-test.adyen.com/v3/companies/{companyId}/webhooks ```  ## Going live  To access the live endpoints, you need an API key from your live Customer Area. Use this API key to make requests to:  ```text https://management-live.adyen.com/v3 ```  ## Release notes Have a look at the [release notes](https://docs.adyen.com/release-notes/management-api) to find out what changed in this version!
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.adyen.model.management

import com.adyen.model.management.AllowedOrigin
import com.adyen.model.management.ApiCredentialLinks

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param active Indicates if the API credential is enabled. Must be set to **true** to use the credential in your integration.
 * @param allowedIpAddresses List of IP addresses from which your client can make requests.  If the list is empty, we allow requests from any IP. If the list is not empty and we get a request from an IP which is not on the list, you get a security error.
 * @param clientKey Public key used for [client-side authentication](https://docs.adyen.com/development-resources/client-side-authentication). The client key is required for Drop-in and Components integrations.
 * @param id Unique identifier of the API credential.
 * @param roles List of [roles](https://docs.adyen.com/development-resources/api-credentials#roles-1) for the API credential.
 * @param username The name of the [API credential](https://docs.adyen.com/development-resources/api-credentials), for example **ws@Company.TestCompany**.
 * @param links 
 * @param allowedOrigins List containing the [allowed origins](https://docs.adyen.com/development-resources/client-side-authentication#allowed-origins) linked to the API credential.
 * @param associatedMerchantAccounts List of merchant accounts that the API credential has explicit access to.   If the credential has access to a company, this implies access to all merchant accounts and no merchants for that company will be included.
 * @param companyName Name of the company linked to the API credential.
 * @param description Description of the API credential.
 */
@Serializable
data class MeApiCredential (

    /* Indicates if the API credential is enabled. Must be set to **true** to use the credential in your integration. */
    @SerialName(value = "active") @Required val active: kotlin.Boolean,

    /* List of IP addresses from which your client can make requests.  If the list is empty, we allow requests from any IP. If the list is not empty and we get a request from an IP which is not on the list, you get a security error. */
    @SerialName(value = "allowedIpAddresses") @Required val allowedIpAddresses: kotlin.collections.List<kotlin.String>,

    /* Public key used for [client-side authentication](https://docs.adyen.com/development-resources/client-side-authentication). The client key is required for Drop-in and Components integrations. */
    @SerialName(value = "clientKey") @Required val clientKey: kotlin.String,

    /* Unique identifier of the API credential. */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* List of [roles](https://docs.adyen.com/development-resources/api-credentials#roles-1) for the API credential. */
    @SerialName(value = "roles") @Required val roles: kotlin.collections.List<kotlin.String>,

    /* The name of the [API credential](https://docs.adyen.com/development-resources/api-credentials), for example **ws@Company.TestCompany**. */
    @SerialName(value = "username") @Required val username: kotlin.String,

    @SerialName(value = "_links") val links: ApiCredentialLinks? = null,

    /* List containing the [allowed origins](https://docs.adyen.com/development-resources/client-side-authentication#allowed-origins) linked to the API credential. */
    @SerialName(value = "allowedOrigins") val allowedOrigins: kotlin.collections.List<AllowedOrigin>? = null,

    /* List of merchant accounts that the API credential has explicit access to.   If the credential has access to a company, this implies access to all merchant accounts and no merchants for that company will be included. */
    @SerialName(value = "associatedMerchantAccounts") val associatedMerchantAccounts: kotlin.collections.List<kotlin.String>? = null,

    /* Name of the company linked to the API credential. */
    @SerialName(value = "companyName") val companyName: kotlin.String? = null,

    /* Description of the API credential. */
    @SerialName(value = "description") val description: kotlin.String? = null

)

