/**
 * Authentication webhooks
 *
 * Adyen sends webhooks to inform your system about events related to cardholder authentication.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.adyen.model.acswebhooks

import com.adyen.model.acswebhooks.AuthenticationNotificationData

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param `data` 
 * @param environment The environment from which the webhook originated.  Possible values: **test**, **live**.
 * @param type Type of notification.
 */
@Serializable
data class AuthenticationNotificationRequest (

    @SerialName(value = "data") @Required val `data`: AuthenticationNotificationData,

    /* The environment from which the webhook originated.  Possible values: **test**, **live**. */
    @SerialName(value = "environment") @Required val environment: kotlin.String,

    /* Type of notification. */
    @SerialName(value = "type") @Required val type: AuthenticationNotificationRequest.Type

) {

    /**
     * Type of notification.
     *
     * Values: BalancePlatformPeriodAuthenticationPeriodCreated
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "balancePlatform.authentication.created") BalancePlatformPeriodAuthenticationPeriodCreated("balancePlatform.authentication.created");
    }
}

