/**
 * Authentication webhooks
 *
 * Adyen sends webhooks to inform your system about events related to cardholder authentication.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.adyen.model.acswebhooks


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param flow The flow used in the challenge. Possible values:  * **OTP_SMS**: one-time password (OTP) flow * **OOB**: out-of-band (OOB) flow
 * @param lastInteraction The last time of interaction with the challenge.
 * @param challengeCancel Indicator informing the Access Control Server (ACS) and the Directory Server (DS) that the authentication has been cancelled. For possible values, refer to [3D Secure API reference](https://docs.adyen.com/online-payments/3d-secure/api-reference#mpidata).
 * @param phoneNumber The last four digits of the phone number used in the challenge.
 * @param resends The number of times the one-time password (OTP) was resent during the challenge.
 * @param retries The number of retries used in the challenge.
 */
@Serializable
data class ChallengeInfo (

    /* The flow used in the challenge. Possible values:  * **OTP_SMS**: one-time password (OTP) flow * **OOB**: out-of-band (OOB) flow */
    @SerialName(value = "flow") @Required val flow: ChallengeInfo.Flow,

    /* The last time of interaction with the challenge. */
    @SerialName(value = "lastInteraction") @Required val lastInteraction: kotlin.String,

    /* Indicator informing the Access Control Server (ACS) and the Directory Server (DS) that the authentication has been cancelled. For possible values, refer to [3D Secure API reference](https://docs.adyen.com/online-payments/3d-secure/api-reference#mpidata). */
    @SerialName(value = "challengeCancel") val challengeCancel: ChallengeInfo.ChallengeCancel? = null,

    /* The last four digits of the phone number used in the challenge. */
    @SerialName(value = "phoneNumber") val phoneNumber: kotlin.String? = null,

    /* The number of times the one-time password (OTP) was resent during the challenge. */
    @SerialName(value = "resends") val resends: kotlin.Int? = null,

    /* The number of retries used in the challenge. */
    @SerialName(value = "retries") val retries: kotlin.Int? = null

) {

    /**
     * The flow used in the challenge. Possible values:  * **OTP_SMS**: one-time password (OTP) flow * **OOB**: out-of-band (OOB) flow
     *
     * Values: OTPSMS,OOB
     */
    @Serializable
    enum class Flow(val value: kotlin.String) {
        @SerialName(value = "OTP_SMS") OTPSMS("OTP_SMS"),
        @SerialName(value = "OOB") OOB("OOB");
    }
    /**
     * Indicator informing the Access Control Server (ACS) and the Directory Server (DS) that the authentication has been cancelled. For possible values, refer to [3D Secure API reference](https://docs.adyen.com/online-payments/3d-secure/api-reference#mpidata).
     *
     * Values: _01,_02,_03,_04,_05,_06,_07
     */
    @Serializable
    enum class ChallengeCancel(val value: kotlin.String) {
        @SerialName(value = "01") _01("01"),
        @SerialName(value = "02") _02("02"),
        @SerialName(value = "03") _03("03"),
        @SerialName(value = "04") _04("04"),
        @SerialName(value = "05") _05("05"),
        @SerialName(value = "06") _06("06"),
        @SerialName(value = "07") _07("07");
    }
}

