/**
 * Adyen Checkout API
 *
 * Adyen Checkout API provides a simple and flexible way to initiate and authorise online payments. You can use the same integration for payments made with cards (including 3D Secure), mobile wallets, and local payment methods (for example, iDEAL and Sofort).  This API reference provides information on available endpoints and how to interact with them. To learn more about the API, visit [online payments documentation](https://docs.adyen.com/online-payments).  ## Authentication Each request to Checkout API must be signed with an API key. For this, [get your API key](https://docs.adyen.com/development-resources/api-credentials#generate-api-key) from your Customer Area, and set this key to the `X-API-Key` header value, for example:  ``` curl -H \"Content-Type: application/json\" \\ -H \"X-API-Key: YOUR_API_KEY\" \\ ... ``` ## Versioning Checkout API supports [versioning](https://docs.adyen.com/development-resources/versioning) using a version suffix in the endpoint URL. This suffix has the following format: \"vXX\", where XX is the version number.  For example: ``` https://checkout-test.adyen.com/v71/payments ```  ## Going live  To access the live endpoints, you need an API key from your live Customer Area.  The live endpoint URLs contain a prefix which is unique to your company account, for example: ``` https://{PREFIX}-checkout-live.adyenpayments.com/checkout/v71/payments ```  Get your `{PREFIX}` from your live Customer Area under **Developers** > **API URLs** > **Prefix**.  When preparing to do live transactions with Checkout API, follow the [go-live checklist](https://docs.adyen.com/online-payments/go-live-checklist) to make sure you've got all the required configuration in place.  ## Release notes Have a look at the [release notes](https://docs.adyen.com/online-payments/release-notes?integration_type=api&version=71) to find out what changed in this version!
 *
 * The version of the OpenAPI document: 71
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.adyen.model.checkout


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param type **nativeRedirect**
 * @param `data` When the redirect URL must be accessed via POST, use this data to post to the redirect URL.
 * @param method Specifies the HTTP method, for example GET or POST.
 * @param nativeRedirectData Native SDK's redirect data containing the direct issuer link and state data that must be submitted to the /v1/nativeRedirect/redirectResult.
 * @param paymentMethodType Specifies the payment method.
 * @param url Specifies the URL to redirect to.
 */
@Serializable
data class CheckoutNativeRedirectAction (

    /* **nativeRedirect** */
    @SerialName(value = "type") @Required val type: CheckoutNativeRedirectAction.Type,

    /* When the redirect URL must be accessed via POST, use this data to post to the redirect URL. */
    @SerialName(value = "data") val `data`: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* Specifies the HTTP method, for example GET or POST. */
    @SerialName(value = "method") val method: kotlin.String? = null,

    /* Native SDK's redirect data containing the direct issuer link and state data that must be submitted to the /v1/nativeRedirect/redirectResult. */
    @SerialName(value = "nativeRedirectData") val nativeRedirectData: kotlin.String? = null,

    /* Specifies the payment method. */
    @SerialName(value = "paymentMethodType") val paymentMethodType: kotlin.String? = null,

    /* Specifies the URL to redirect to. */
    @SerialName(value = "url") val url: kotlin.String? = null

) {

    /**
     * **nativeRedirect**
     *
     * Values: NativeRedirect
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "nativeRedirect") NativeRedirect("nativeRedirect");
    }
}

