/**
 * Configuration webhooks
 *
 * Adyen sends webhooks to inform your system about events that occur in your platform. These events include, for example, when an account holder's capabilities are updated, or when a sweep configuration is created or updated.  When an event occurs, Adyen makes an HTTP POST request to a URL on your server and includes the details of the event in the request body.  You can use these webhooks to build your implementation. For example, you can use this information to update internal statuses when the status of a capability is changed.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.adyen.model.configurationwebhooks


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param country The two-character ISO-3166-1 alpha-2 country code. For example, **US**.
 * @param city The name of the city.
 * @param company The name of the company.
 * @param email The email address.
 * @param houseNumberOrName The house number or name.
 * @param mobile The full telephone number.
 * @param postalCode The postal code.  Maximum length:  * 5 digits for addresses in the US.  * 10 characters for all other countries.
 * @param stateOrProvince The two-letter ISO 3166-2 state or province code.  Maximum length: 2 characters for addresses in the US.
 * @param street The streetname of the house.
 */
@Serializable
data class BulkAddress (

    /* The two-character ISO-3166-1 alpha-2 country code. For example, **US**. */
    @SerialName(value = "country") @Required val country: kotlin.String,

    /* The name of the city. */
    @SerialName(value = "city") val city: kotlin.String? = null,

    /* The name of the company. */
    @SerialName(value = "company") val company: kotlin.String? = null,

    /* The email address. */
    @SerialName(value = "email") val email: kotlin.String? = null,

    /* The house number or name. */
    @SerialName(value = "houseNumberOrName") val houseNumberOrName: kotlin.String? = null,

    /* The full telephone number. */
    @SerialName(value = "mobile") val mobile: kotlin.String? = null,

    /* The postal code.  Maximum length:  * 5 digits for addresses in the US.  * 10 characters for all other countries. */
    @SerialName(value = "postalCode") val postalCode: kotlin.String? = null,

    /* The two-letter ISO 3166-2 state or province code.  Maximum length: 2 characters for addresses in the US. */
    @SerialName(value = "stateOrProvince") val stateOrProvince: kotlin.String? = null,

    /* The streetname of the house. */
    @SerialName(value = "street") val street: kotlin.String? = null

)

