/**
 * Configuration API
 *
 * The Configuration API enables you to create a platform where you can onboard your users as account holders and create balance accounts, cards, and business accounts.  ## Authentication Your Adyen contact will provide your API credential and an API key. To connect to the API, add an `X-API-Key` header with the API key as the value, for example:   ``` curl -H \"Content-Type: application/json\" \\ -H \"X-API-Key: YOUR_API_KEY\" \\ ... ```  Alternatively, you can use the username and password to connect to the API using basic authentication. For example:  ``` curl -H \"Content-Type: application/json\" \\ -U \"ws@BalancePlatform.YOUR_BALANCE_PLATFORM\":\"YOUR_WS_PASSWORD\" \\ ... ``` ## Versioning The Configuration API supports [versioning](https://docs.adyen.com/development-resources/versioning) using a version suffix in the endpoint URL. This suffix has the following format: \"vXX\", where XX is the version number.  For example: ``` https://balanceplatform-api-test.adyen.com/bcl/v2/accountHolders ``` ## Going live When going live, your Adyen contact will provide your API credential for the live environment. You can then use the API key or the username and password to send requests to `https://balanceplatform-api-live.adyen.com/bcl/v2`.
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.adyen.model.balanceplatform

import com.adyen.model.balanceplatform.InvalidField

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param detail A human-readable explanation specific to this occurrence of the problem.
 * @param errorCode A code that identifies the problem type.
 * @param status The HTTP status code.
 * @param title A short, human-readable summary of the problem type.
 * @param type A URI that identifies the problem type, pointing to human-readable documentation on this problem type.
 * @param instance A unique URI that identifies the specific occurrence of the problem.
 * @param invalidFields Detailed explanation of each validation error, when applicable.
 * @param requestId A unique reference for the request, essentially the same as `pspReference`.
 * @param response 
 */
@Serializable
data class RestServiceError (

    /* A human-readable explanation specific to this occurrence of the problem. */
    @SerialName(value = "detail") @Required val detail: kotlin.String,

    /* A code that identifies the problem type. */
    @SerialName(value = "errorCode") @Required val errorCode: kotlin.String,

    /* The HTTP status code. */
    @SerialName(value = "status") @Required val status: kotlin.Int,

    /* A short, human-readable summary of the problem type. */
    @SerialName(value = "title") @Required val title: kotlin.String,

    /* A URI that identifies the problem type, pointing to human-readable documentation on this problem type. */
    @SerialName(value = "type") @Required val type: kotlin.String,

    /* A unique URI that identifies the specific occurrence of the problem. */
    @SerialName(value = "instance") val instance: kotlin.String? = null,

    /* Detailed explanation of each validation error, when applicable. */
    @SerialName(value = "invalidFields") val invalidFields: kotlin.collections.List<InvalidField>? = null,

    /* A unique reference for the request, essentially the same as `pspReference`. */
    @SerialName(value = "requestId") val requestId: kotlin.String? = null,

    @SerialName(value = "response") val response: kotlin.String? = null

)

