/**
 * Configuration API
 *
 * The Configuration API enables you to create a platform where you can onboard your users as account holders and create balance accounts, cards, and business accounts.  ## Authentication Your Adyen contact will provide your API credential and an API key. To connect to the API, add an `X-API-Key` header with the API key as the value, for example:   ``` curl -H \"Content-Type: application/json\" \\ -H \"X-API-Key: YOUR_API_KEY\" \\ ... ```  Alternatively, you can use the username and password to connect to the API using basic authentication. For example:  ``` curl -H \"Content-Type: application/json\" \\ -U \"ws@BalancePlatform.YOUR_BALANCE_PLATFORM\":\"YOUR_WS_PASSWORD\" \\ ... ``` ## Versioning The Configuration API supports [versioning](https://docs.adyen.com/development-resources/versioning) using a version suffix in the endpoint URL. This suffix has the following format: \"vXX\", where XX is the version number.  For example: ``` https://balanceplatform-api-test.adyen.com/bcl/v2/accountHolders ``` ## Going live When going live, your Adyen contact will provide your API credential for the live environment. You can then use the API key or the username and password to send requests to `https://balanceplatform-api-live.adyen.com/bcl/v2`.
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.adyen.model.balanceplatform

import com.adyen.model.balanceplatform.TransferRouteRequirements

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param category  The type of transfer.   Possible values:    - **bank**: Transfer to a [transfer instrument](https://docs.adyen.com/api-explorer/#/legalentity/latest/post/transferInstruments__resParam_id) or a bank account. 
 * @param country The two-character ISO-3166-1 alpha-2 country code of the counterparty. For example, **US** or **NL**.
 * @param currency The three-character ISO currency code of transfer. For example, **USD** or **EUR**.
 * @param priority The priority for the bank transfer. This sets the speed at which the transfer is sent and the fees that you have to pay. Possible values:  * **regular**: For normal, low-value transactions.  * **fast**: Faster way to transfer funds but has higher fees. Recommended for high-priority, low-value transactions.  * **wire**: Fastest way to transfer funds but has the highest fees. Recommended for high-priority, high-value transactions.  * **instant**: Instant way to transfer funds in [SEPA countries](https://www.ecb.europa.eu/paym/integration/retail/sepa/html/index.en.html).  * **crossBorder**: High-value transfer to a recipient in a different country.  * **internal**: Transfer to an Adyen-issued business bank account (by bank account number/IBAN).
 * @param requirements 
 */
@Serializable
data class TransferRoute (

    /*  The type of transfer.   Possible values:    - **bank**: Transfer to a [transfer instrument](https://docs.adyen.com/api-explorer/#/legalentity/latest/post/transferInstruments__resParam_id) or a bank account.  */
    @SerialName(value = "category") val category: TransferRoute.Category? = null,

    /* The two-character ISO-3166-1 alpha-2 country code of the counterparty. For example, **US** or **NL**. */
    @SerialName(value = "country") val country: kotlin.String? = null,

    /* The three-character ISO currency code of transfer. For example, **USD** or **EUR**. */
    @SerialName(value = "currency") val currency: kotlin.String? = null,

    /* The priority for the bank transfer. This sets the speed at which the transfer is sent and the fees that you have to pay. Possible values:  * **regular**: For normal, low-value transactions.  * **fast**: Faster way to transfer funds but has higher fees. Recommended for high-priority, low-value transactions.  * **wire**: Fastest way to transfer funds but has the highest fees. Recommended for high-priority, high-value transactions.  * **instant**: Instant way to transfer funds in [SEPA countries](https://www.ecb.europa.eu/paym/integration/retail/sepa/html/index.en.html).  * **crossBorder**: High-value transfer to a recipient in a different country.  * **internal**: Transfer to an Adyen-issued business bank account (by bank account number/IBAN). */
    @SerialName(value = "priority") val priority: TransferRoute.Priority? = null,

    @SerialName(value = "requirements") val requirements: TransferRouteRequirements? = null

) {

    /**
     *  The type of transfer.   Possible values:    - **bank**: Transfer to a [transfer instrument](https://docs.adyen.com/api-explorer/#/legalentity/latest/post/transferInstruments__resParam_id) or a bank account. 
     *
     * Values: Bank,Card,Grants,Internal,IssuedCard,Migration,PlatformPayment,TopUp,Upgrade
     */
    @Serializable
    enum class Category(val value: kotlin.String) {
        @SerialName(value = "bank") Bank("bank"),
        @SerialName(value = "card") Card("card"),
        @SerialName(value = "grants") Grants("grants"),
        @SerialName(value = "internal") Internal("internal"),
        @SerialName(value = "issuedCard") IssuedCard("issuedCard"),
        @SerialName(value = "migration") Migration("migration"),
        @SerialName(value = "platformPayment") PlatformPayment("platformPayment"),
        @SerialName(value = "topUp") TopUp("topUp"),
        @SerialName(value = "upgrade") Upgrade("upgrade");
    }
    /**
     * The priority for the bank transfer. This sets the speed at which the transfer is sent and the fees that you have to pay. Possible values:  * **regular**: For normal, low-value transactions.  * **fast**: Faster way to transfer funds but has higher fees. Recommended for high-priority, low-value transactions.  * **wire**: Fastest way to transfer funds but has the highest fees. Recommended for high-priority, high-value transactions.  * **instant**: Instant way to transfer funds in [SEPA countries](https://www.ecb.europa.eu/paym/integration/retail/sepa/html/index.en.html).  * **crossBorder**: High-value transfer to a recipient in a different country.  * **internal**: Transfer to an Adyen-issued business bank account (by bank account number/IBAN).
     *
     * Values: CrossBorder,Fast,Instant,Internal,Regular,Wire
     */
    @Serializable
    enum class Priority(val value: kotlin.String) {
        @SerialName(value = "crossBorder") CrossBorder("crossBorder"),
        @SerialName(value = "fast") Fast("fast"),
        @SerialName(value = "instant") Instant("instant"),
        @SerialName(value = "internal") Internal("internal"),
        @SerialName(value = "regular") Regular("regular"),
        @SerialName(value = "wire") Wire("wire");
    }
}

