/**
 * Transfer webhooks
 *
 * Adyen sends webhooks to inform your system about incoming and outgoing transfers in your platform.  You can use these webhooks to build your implementation. For example, you can use this information to update balances in your own dashboards or to keep track of incoming funds.
 *
 * The version of the OpenAPI document: 4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.adyen.model.transferwebhooks


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param accountNumber The 9- to 15-character bank account number (alphanumeric), without separators or whitespace. Starts with the 3-digit branch code.
 * @param clearingCode The 3-digit clearing code, without separators or whitespace.
 * @param type **hkLocal**
 */
@Serializable
data class HKLocalAccountIdentification (

    /* The 9- to 15-character bank account number (alphanumeric), without separators or whitespace. Starts with the 3-digit branch code. */
    @SerialName(value = "accountNumber") @Required val accountNumber: kotlin.String,

    /* The 3-digit clearing code, without separators or whitespace. */
    @SerialName(value = "clearingCode") @Required val clearingCode: kotlin.String,

    /* **hkLocal** */
    @SerialName(value = "type") @Required val type: HKLocalAccountIdentification.Type = Type.HkLocal

) {

    /**
     * **hkLocal**
     *
     * Values: HkLocal
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "hkLocal") HkLocal("hkLocal");
    }
}

