/**
 * Transfer webhooks
 *
 * Adyen sends webhooks to inform your system about incoming and outgoing transfers in your platform.  You can use these webhooks to build your implementation. For example, you can use this information to update balances in your own dashboards or to keep track of incoming funds.
 *
 * The version of the OpenAPI document: 4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.adyen.model.transferwebhooks


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param city The city where the merchant is located.
 * @param country The country where the merchant is located in [three-letter country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) format.
 * @param countryOfOrigin The home country in [three-digit country code](https://en.wikipedia.org/wiki/ISO_3166-1_numeric) format, used for government-controlled merchants such as embassies.
 * @param name The name of the merchant's shop or service.
 * @param rawData The raw data.
 * @param state The state where the merchant is located.
 */
@Serializable
data class NameLocation (

    /* The city where the merchant is located. */
    @SerialName(value = "city") val city: kotlin.String? = null,

    /* The country where the merchant is located in [three-letter country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) format. */
    @SerialName(value = "country") val country: kotlin.String? = null,

    /* The home country in [three-digit country code](https://en.wikipedia.org/wiki/ISO_3166-1_numeric) format, used for government-controlled merchants such as embassies. */
    @SerialName(value = "countryOfOrigin") val countryOfOrigin: kotlin.String? = null,

    /* The name of the merchant's shop or service. */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The raw data. */
    @SerialName(value = "rawData") val rawData: kotlin.String? = null,

    /* The state where the merchant is located. */
    @SerialName(value = "state") val state: kotlin.String? = null

)

