/**
 * Transfer webhooks
 *
 * Adyen sends webhooks to inform your system about incoming and outgoing transfers in your platform.  You can use these webhooks to build your implementation. For example, you can use this information to update balances in your own dashboards or to keep track of incoming funds.
 *
 * The version of the OpenAPI document: 4
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.adyen.model.transferwebhooks


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param accountNumber The 15-16 digit bank account number. The first 2 digits are the bank number, the next 4 digits are the branch number, the next 7 digits are the account number, and the final 2-3 digits are the suffix.
 * @param type **nzLocal**
 */
@Serializable
data class NZLocalAccountIdentification (

    /* The 15-16 digit bank account number. The first 2 digits are the bank number, the next 4 digits are the branch number, the next 7 digits are the account number, and the final 2-3 digits are the suffix. */
    @SerialName(value = "accountNumber") @Required val accountNumber: kotlin.String,

    /* **nzLocal** */
    @SerialName(value = "type") @Required val type: NZLocalAccountIdentification.Type = Type.NzLocal

) {

    /**
     * **nzLocal**
     *
     * Values: NzLocal
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "nzLocal") NzLocal("nzLocal");
    }
}

