/**
 * Adyen Recurring API
 *
 * The Recurring APIs allow you to manage and remove your tokens or saved payment details. Tokens should be created with validation during a payment request.  For more information, refer to our [Tokenization documentation](https://docs.adyen.com/online-payments/tokenization). ## Authentication You need an [API credential](https://docs.adyen.com/development-resources/api-credentials) to authenticate to the API.  If using an API key, add an `X-API-Key` header with the API key as the value, for example:   ``` curl -H \"Content-Type: application/json\" \\ -H \"X-API-Key: YOUR_API_KEY\" \\ ... ```  Alternatively, you can use the username and password to connect to the API using basic authentication, for example:  ``` curl -U \"ws@Company.YOUR_COMPANY_ACCOUNT\":\"YOUR_BASIC_AUTHENTICATION_PASSWORD\" \\ -H \"Content-Type: application/json\" \\ ... ```  ## Versioning Recurring API supports [versioning](https://docs.adyen.com/development-resources/versioning) using a version suffix in the endpoint URL. This suffix has the following format: \"vXX\", where XX is the version number.  For example: ``` https://pal-test.adyen.com/pal/servlet/Recurring/v68/disable ```  ## Going live  To authenticate to the live endpoints, you need an [API credential](https://docs.adyen.com/development-resources/api-credentials) from your live Customer Area.  The live endpoint URLs contain a prefix which is unique to your company account: ```  https://{PREFIX}-pal-live.adyenpayments.com/pal/servlet/Recurring/v68/disable ```  Get your `{PREFIX}` from your live Customer Area under **Developers** > **API URLs** > **Prefix**.
 *
 * The version of the OpenAPI document: 68
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.adyen.model.recurring

import com.adyen.model.recurring.Amount

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param amount 
 * @param merchantAccount The merchant account identifier with which you want to process the transaction.
 * @param reference Pre-debit notification reference sent by the merchant. This is a mandatory field
 * @param shopperReference The ID that uniquely identifies the shopper.  This `shopperReference` must be the same as the `shopperReference` used in the initial payment.
 * @param billingDate Date on which the subscription amount will be debited from the shopper. In YYYY-MM-DD format
 * @param billingSequenceNumber Sequence of the debit. Depends on Frequency and Billing Attempts Rule.
 * @param displayedReference Reference of Pre-debit notification that is displayed to the shopper. Optional field. Maps to reference if missing
 * @param recurringDetailReference This is the `recurringDetailReference` returned in the response when you created the token.
 * @param storedPaymentMethodId This is the `recurringDetailReference` returned in the response when you created the token.
 */
@Serializable
data class NotifyShopperRequest (

    @SerialName(value = "amount") @Required val amount: Amount,

    /* The merchant account identifier with which you want to process the transaction. */
    @SerialName(value = "merchantAccount") @Required val merchantAccount: kotlin.String,

    /* Pre-debit notification reference sent by the merchant. This is a mandatory field */
    @SerialName(value = "reference") @Required val reference: kotlin.String,

    /* The ID that uniquely identifies the shopper.  This `shopperReference` must be the same as the `shopperReference` used in the initial payment. */
    @SerialName(value = "shopperReference") @Required val shopperReference: kotlin.String,

    /* Date on which the subscription amount will be debited from the shopper. In YYYY-MM-DD format */
    @SerialName(value = "billingDate") val billingDate: kotlin.String? = null,

    /* Sequence of the debit. Depends on Frequency and Billing Attempts Rule. */
    @SerialName(value = "billingSequenceNumber") val billingSequenceNumber: kotlin.String? = null,

    /* Reference of Pre-debit notification that is displayed to the shopper. Optional field. Maps to reference if missing */
    @SerialName(value = "displayedReference") val displayedReference: kotlin.String? = null,

    /* This is the `recurringDetailReference` returned in the response when you created the token. */
    @SerialName(value = "recurringDetailReference") val recurringDetailReference: kotlin.String? = null,

    /* This is the `recurringDetailReference` returned in the response when you created the token. */
    @SerialName(value = "storedPaymentMethodId") val storedPaymentMethodId: kotlin.String? = null

)

