/**
 * Adyen Recurring API
 *
 * The Recurring APIs allow you to manage and remove your tokens or saved payment details. Tokens should be created with validation during a payment request.  For more information, refer to our [Tokenization documentation](https://docs.adyen.com/online-payments/tokenization). ## Authentication You need an [API credential](https://docs.adyen.com/development-resources/api-credentials) to authenticate to the API.  If using an API key, add an `X-API-Key` header with the API key as the value, for example:   ``` curl -H \"Content-Type: application/json\" \\ -H \"X-API-Key: YOUR_API_KEY\" \\ ... ```  Alternatively, you can use the username and password to connect to the API using basic authentication, for example:  ``` curl -U \"ws@Company.YOUR_COMPANY_ACCOUNT\":\"YOUR_BASIC_AUTHENTICATION_PASSWORD\" \\ -H \"Content-Type: application/json\" \\ ... ```  ## Versioning Recurring API supports [versioning](https://docs.adyen.com/development-resources/versioning) using a version suffix in the endpoint URL. This suffix has the following format: \"vXX\", where XX is the version number.  For example: ``` https://pal-test.adyen.com/pal/servlet/Recurring/v68/disable ```  ## Going live  To authenticate to the live endpoints, you need an [API credential](https://docs.adyen.com/development-resources/api-credentials) from your live Customer Area.  The live endpoint URLs contain a prefix which is unique to your company account: ```  https://{PREFIX}-pal-live.adyenpayments.com/pal/servlet/Recurring/v68/disable ```  Get your `{PREFIX}` from your live Customer Area under **Developers** > **API URLs** > **Prefix**.
 *
 * The version of the OpenAPI document: 68
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.adyen.model.recurring

import com.adyen.model.recurring.Address
import com.adyen.model.recurring.BankAccount
import com.adyen.model.recurring.Card
import com.adyen.model.recurring.Name
import com.adyen.model.recurring.TokenDetails

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param recurringDetailReference The reference that uniquely identifies the recurring detail.
 * @param variant The payment method, such as “mc\", \"visa\", \"ideal\", \"paypal\".
 * @param additionalData This field contains additional data, which may be returned in a particular response.  The additionalData object consists of entries, each of which includes the key and value.
 * @param alias The alias of the credit card number.  Applies only to recurring contracts storing credit card details
 * @param aliasType The alias type of the credit card number.  Applies only to recurring contracts storing credit card details.
 * @param bank 
 * @param billingAddress 
 * @param card 
 * @param contractTypes Types of recurring contracts.
 * @param creationDate The date when the recurring details were created.
 * @param firstPspReference The `pspReference` of the first recurring payment that created the recurring detail.
 * @param name An optional descriptive name for this recurring detail.
 * @param networkTxReference Returned in the response if you are not tokenizing with Adyen and are using the Merchant-initiated transactions (MIT) framework from Mastercard or Visa.  This contains either the Mastercard Trace ID or the Visa Transaction ID.
 * @param paymentMethodVariant The  type or sub-brand of a payment method used, e.g. Visa Debit, Visa Corporate, etc. For more information, refer to [PaymentMethodVariant](https://docs.adyen.com/development-resources/paymentmethodvariant).
 * @param shopperName 
 * @param socialSecurityNumber A shopper's social security number (only in countries where it is legal to collect).
 * @param tokenDetails 
 */
@Serializable
data class RecurringDetail (

    /* The reference that uniquely identifies the recurring detail. */
    @SerialName(value = "recurringDetailReference") @Required val recurringDetailReference: kotlin.String,

    /* The payment method, such as “mc\", \"visa\", \"ideal\", \"paypal\". */
    @SerialName(value = "variant") @Required val variant: kotlin.String,

    /* This field contains additional data, which may be returned in a particular response.  The additionalData object consists of entries, each of which includes the key and value. */
    @SerialName(value = "additionalData") val additionalData: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* The alias of the credit card number.  Applies only to recurring contracts storing credit card details */
    @SerialName(value = "alias") val alias: kotlin.String? = null,

    /* The alias type of the credit card number.  Applies only to recurring contracts storing credit card details. */
    @SerialName(value = "aliasType") val aliasType: kotlin.String? = null,

    @SerialName(value = "bank") val bank: BankAccount? = null,

    @SerialName(value = "billingAddress") val billingAddress: Address? = null,

    @SerialName(value = "card") val card: Card? = null,

    /* Types of recurring contracts. */
    @SerialName(value = "contractTypes") val contractTypes: kotlin.collections.List<kotlin.String>? = null,

    /* The date when the recurring details were created. */
    @SerialName(value = "creationDate") val creationDate: kotlin.String? = null,

    /* The `pspReference` of the first recurring payment that created the recurring detail. */
    @SerialName(value = "firstPspReference") val firstPspReference: kotlin.String? = null,

    /* An optional descriptive name for this recurring detail. */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* Returned in the response if you are not tokenizing with Adyen and are using the Merchant-initiated transactions (MIT) framework from Mastercard or Visa.  This contains either the Mastercard Trace ID or the Visa Transaction ID. */
    @SerialName(value = "networkTxReference") val networkTxReference: kotlin.String? = null,

    /* The  type or sub-brand of a payment method used, e.g. Visa Debit, Visa Corporate, etc. For more information, refer to [PaymentMethodVariant](https://docs.adyen.com/development-resources/paymentmethodvariant). */
    @SerialName(value = "paymentMethodVariant") val paymentMethodVariant: kotlin.String? = null,

    @SerialName(value = "shopperName") val shopperName: Name? = null,

    /* A shopper's social security number (only in countries where it is legal to collect). */
    @SerialName(value = "socialSecurityNumber") val socialSecurityNumber: kotlin.String? = null,

    @SerialName(value = "tokenDetails") val tokenDetails: TokenDetails? = null

)

